### ISSUE TITLE
Update to 8u72

### ISSUE THREAD

**Issue by codefromthecrypt** [delitescere/docker-zulu#5]
Looks like there's a Zulu update available. Mind giving this a bump?

**Comment by hmalphettes** [comment]
I am working on a PR to help with this but I can't find the new jre file: `zre1.8.0_60-8.9.0.4-compact3-x86lx64.txz`

**Comment by hmalphettes** [comment]
I followed-up on the zulu's forum: http://zulu.org/forum/thread/jre-compact3-download/
Cheers!

**Comment by codefromthecrypt** [comment]
thanks so much for chasing this

**Comment by hmalphettes** [comment]
@adriancole @delitescere we have an answer:
http://zulu.org/forum/thread/jre-compact3-download/

The zulu guys are fine providing on an ad-hoc basis a JRE compact3 build.
If a sufficient number of community users request it they will consider providing it on a regular basis.

@delitescere Thanks for requesting such a build in the first place.

**Comment by delitescere** [comment]
I have just been provided 8u72 cp3. This will take me a few days to test and update to dockerhub. I'll update the JDK image too.

I've also requested cp1 but it's still going through TCK on busybox.

**Comment by hmalphettes** [comment]
@delitescere many thanks again!

**Comment by delitescere** [comment]
8u72 cp3 now deployed to docker hub
