### ISSUE TITLE
Provide a smaller zulu-jre image

### ISSUE THREAD

**Issue by hmalphettes** [delitescere/docker-zulu#6]
Hi there and many thanks for this!

As we are trying to make the smallest possible image, I understand we can leave as an exercise to the reader to build their own image, squash it and upload it to a docker hub.

Here is an attempt at providing that out of the box for the jre:
https://github.com/hmalphettes/docker-alpine-zulujre

The generated image is less than 67MB and most likely does not need to be squashed:
https://hub.docker.com/r/hmalphettes/alpine-zulujre/tags/

**Comment by delitescere** [comment]
I'm waiting on the cp1 binary to come from Azul, it's still going through TCK certification on busybox. It should be quite a bit smaller.

I'm also working on a Java 9 version which will be custom per-app (Jigsawed) but should be <10MB generally.

**Comment by hmalphettes** [comment]
@delitescere That is fantastic! Thanks for all this work.

**Comment by delitescere** [comment]
I've taken some of the steps from your Dockerfile (thanks for the tips). We come in at the same size now, for 8u72 and above.

I've removed the common base images, and removed as many layers as possible.

**Comment by hmalphettes** [comment]
All right: I added a deprecation note to my repository.
I switched to using your image for my elasticsearch container.
Cheers!
