### ISSUE TITLE
Update to 8u92

### ISSUE THREAD

**Issue by codefromthecrypt** [delitescere/docker-zulu#8]
#5 has some background. For example, last time @hmalphettes requested a package be made via a user forum

**Comment by jprante** [comment]
Seems that http://zulu.org/forum/thread/jre-compact3-download/ page is 404.

How can I find zulu 8u92 jre compact3 build tar.gz for Alpine/BusyBox?

**Comment by codefromthecrypt** [comment]
looks like someone else (@rijalati) has published a variant with 8u92. Is it possible to update here?

https://hub.docker.com/r/rijalati/alpine-zulu-jdk8/~/dockerfile/

**Comment by jprante** [comment]
http://cdn.azul.com/zulu/bin/zulu8.15.0.1-jdk8.0.92-linux_x64.tar.gz is the ordinary build around 74 MB, a custom Zulu 8u92 compact3 build tar.gz would be around 18 MB.

**Comment by delitescere** [comment]
Both 8u92 and 8u131
